### ISSUE TITLE
get_cns error

### ISSUE THREAD

**Issue by JHAO12321** [Nextomics/NextDenovo#7]
HI,
    I got errors when running get_cns step, the errors are listed below. 
    The 'segmentation fault' also happened at sort_align stage, but disappeared when I rerun the wrong tasks. However, things didn't get well when I rerun the jobs at get_cns stage. 
    Could you help me with the problems?
    Thank you!

 **ERROR 1:** 
/home/SystemSoftware/tsce/torque6/share/nodes1/mom_priv/jobs/1270566.mu01.SC: line 5:   642 Segmentation fault      (core dumped) python /1.Software/NextDenovo/lib/nextCorrector.py -f /nextdenovo/01.correct/.//02.cns_align//01.get_cns.input.idxs -i /nextdenovo/01.correct/01.raw_align/03.sort_align.sh.work/sort_align006/input.seed.088.sorted.ovl -p 20 -max_lq_length 1000 -fast -o cns.fasta

**ERROR 2:**
Traceback (most recent call last):
  File "/1.Software/NextDenovo/lib/nextCorrector.py", line 258, in <module>
    main(args)
  File "/1.Software/NextDenovo/lib/nextCorrector.py", line 198, in main
    worker, read_seq_data(args, corrected_seeds), chunksize=1):
  File "/1.Software/python_lib/nextdenovo/lib/python2.7/multiprocessing/pool.py", line 668, in next
    raise value
SystemError: NULL result without error in PyObject_Call

**ERROR 3:**
*** Error in `python': double free or corruption (out): 0x00002b70bbe79010 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7cfe1)[0x2b6e4bdb0fe1]
/1.Software/NextDenovo/lib/ovlSeq.so(bit2seq+0x1f7)[0x2b6e54d0e867]
/1.Software/python_lib/nextdenovo/lib/python2.7/lib-dynload/_ctypes.so(ffi_call_unix64+0x4c)[0x2b6e548fb35c]
/1.Software/python_lib/nextdenovo/lib/python2.7/lib-dynload/_ctypes.so(ffi_call+0x1f5)[0x2b6e548faab5]
/1.Software/python_lib/nextdenovo/lib/python2.7/lib-dynload/_ctypes.so(_ctypes_callproc+0x3e6)[0x2b6e548f2166]
/1.Software/python_lib/nextdenovo/lib/python2.7/lib-dynload/_ctypes.so(+0x9cf3)[0x2b6e548e9cf3]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x53)[0x2b6e4b071d23]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6a24)[0x2b6e4b122f54]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(+0x6dcec)[0x2b6e4b095cec]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(+0x686cd)[0x2b6e4b0906cd]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x2e1f)[0x2b6e4b11f34f]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(+0x6dcec)[0x2b6e4b095cec]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(+0x686cd)[0x2b6e4b0906cd]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x2e1f)[0x2b6e4b11f34f]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e)[0x2b6e4b125a2e]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(+0x794a8)[0x2b6e4b0a14a8]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x53)[0x2b6e4b071d23]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x6267)[0x2b6e4b122797]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8665)[0x2b6e4b124b95]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(PyEval_EvalFrameEx+0x8665)[0x2b6e4b124b95]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(PyEval_EvalCodeEx+0x89e)[0x2b6e4b125a2e]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(+0x793a1)[0x2b6e4b0a13a1]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x53)[0x2b6e4b071d23]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(+0x5c4bf)[0x2b6e4b0844bf]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(PyObject_Call+0x53)[0x2b6e4b071d23]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(PyEval_CallObjectWithKeywords+0x43)[0x2b6e4b11b633]
/1.Software/python_lib/nextdenovo/bin/../lib/libpython2.7.so.1.0(+0x135d42)[0x2b6e4b15dd42]
/lib64/libpthread.so.0(+0x7dc5)[0x2b6e4b416dc5]
/lib64/libc.so.6(clone+0x6d)[0x2b6e4be2a1cd]
======= Memory map: ========
......
......
/home/SystemSoftware/tsce/torque6/share/nodes2/mom_priv/jobs/1270586.mu01.SC: line 5: 25161 Aborted                 (core dumped) python /1.Software/NextDenovo/lib/nextCorrector.py -f /nextdenovo/01.correct/.//02.cns_align//01.get_cns.input.idxs -i /nextdenovo/01.correct/01.raw_align/03.sort_align.sh.work/sort_align026/input.seed.021.sorted.ovl -p 20 -max_lq_length 1000 -fast -o cns.fasta

**Comment by moold** [comment]
Could you send  the following two files to me by email ?
* /nextdenovo/01.correct/01.raw_align/03.sort_align.sh.work/sort_align006/input.seed.088.sorted.ovl 
* /nextdenovo/01.correct/01.raw_align/.input.seed.088.idx

**Comment by JHAO12321** [comment]
HI,
       Thank you for your immediate reply.
I suspect that the ‘sorted.ovls’ may not have the correct structure due to some problems of the disk and trying to regenerate the files.
       I will rerun the tasks again with the new ovls and will send you the files if the errors still exist.

       Thank you!


Best Regards


发件人: Hu Jiang <notifications@github.com>
答复: Nextomics/NextDenovo <reply@reply.github.com>
日期: 2019年7月17日 星期三 12:28
收件人: Nextomics/NextDenovo <NextDenovo@noreply.github.com>
抄送: "王佳昊(Jiahao Wang)" <wangjiahao@genomics.cn>, Author <author@noreply.github.com>
主题: Re: [Nextomics/NextDenovo] get_cns error (#7)


Could you send the following two files to me by email ?

  *   /nextdenovo/01.correct/01.raw_align/03.sort_align.sh.work/sort_align006/input.seed.088.sorted.ovl
  *   /nextdenovo/01.correct/01.raw_align/.input.seed.088.idx

**Comment by moold** [comment]
OK

**Comment by JHAO12321** [comment]
HI, I have upload the two files, https://pan.genomics.cn/ucdisk/s/MJr2ii.
Besides, I also need to know the reason of other two errors.
Thank you very much!


________________________________
发件人: Hu Jiang <notifications@github.com>
发送时间: 2019年7月17日 18:24
收件人: Nextomics/NextDenovo
抄送: 王佳昊(Jiahao Wang); Author
主题: Re: [Nextomics/NextDenovo] get_cns error (#7)


OK

―

**Comment by moold** [comment]
Hi, I have checked files that your uploaded  and it seems this is a old version bug,  I have fixed in the new version some weeks ago, so pls download the newest version and try again.

**Comment by JHAO12321** [comment]
OK, I will try. Thanks!


Best Regards
Jiahao
wangjiahao@genomics.cn


发件人: Hu Jiang <notifications@github.com>
答复: Nextomics/NextDenovo <reply@reply.github.com>
日期: 2019年7月22日 星期一 13:38
收件人: Nextomics/NextDenovo <NextDenovo@noreply.github.com>
抄送: "王佳昊(Jiahao Wang)" <wangjiahao@genomics.cn>, Author <author@noreply.github.com>
主题: Re: [Nextomics/NextDenovo] get_cns error (#7)


Hi, I have checked files that your uploaded and it seems this is a old version bug, I have fixed in the new version some weeks ago, so pls download the newest version and try again.

**Comment by JHAO12321** [comment]
I download the NextDenovo from github yesterday and rerun the get_cns step but the error still exists. Maybe it is caused by some other reasons. Could you please check again?
Thank you very much!


Best Regards
Jiahao
wangjiahao@genomics.cn


发件人: "王佳昊(Jiahao Wang)" <wangjiahao@genomics.cn>
日期: 2019年7月22日 星期一 14:52
收件人: Nextomics/NextDenovo <reply@reply.github.com>
主题: Re: [Nextomics/NextDenovo] get_cns error (#7)

OK, I will try. Thanks!


Best Regards
Jiahao
wangjiahao@genomics.cn


发件人: Hu Jiang <notifications@github.com>
答复: Nextomics/NextDenovo <reply@reply.github.com>
日期: 2019年7月22日 星期一 13:38
收件人: Nextomics/NextDenovo <NextDenovo@noreply.github.com>
抄送: "王佳昊(Jiahao Wang)" <wangjiahao@genomics.cn>, Author <author@noreply.github.com>
主题: Re: [Nextomics/NextDenovo] get_cns error (#7)


Hi, I have checked files that your uploaded and it seems this is a old version bug, I have fixed in the new version some weeks ago, so pls download the newest version and try again.

**Comment by JHAO12321** [comment]
HI, if it is not easy to solve the problem, could you help me to ignore the reads like this ?
Thank you.


Best Regards
Jiahao
wangjiahao@genomics.cn


发件人: "王佳昊(Jiahao Wang)" <wangjiahao@genomics.cn>
日期: 2019年7月23日 星期二 09:39
收件人: Nextomics/NextDenovo <reply@reply.github.com>
主题: Re: [Nextomics/NextDenovo] get_cns error (#7)

I download the NextDenovo from github yesterday and rerun the get_cns step but the error still exists. Maybe it is caused by some other reasons. Could you please check again?
Thank you very much!


Best Regards
Jiahao
wangjiahao@genomics.cn


发件人: "王佳昊(Jiahao Wang)" <wangjiahao@genomics.cn>
日期: 2019年7月22日 星期一 14:52
收件人: Nextomics/NextDenovo <reply@reply.github.com>
主题: Re: [Nextomics/NextDenovo] get_cns error (#7)

OK, I will try. Thanks!


Best Regards
Jiahao
wangjiahao@genomics.cn


发件人: Hu Jiang <notifications@github.com>
答复: Nextomics/NextDenovo <reply@reply.github.com>
日期: 2019年7月22日 星期一 13:38
收件人: Nextomics/NextDenovo <NextDenovo@noreply.github.com>
抄送: "王佳昊(Jiahao Wang)" <wangjiahao@genomics.cn>, Author <author@noreply.github.com>
主题: Re: [Nextomics/NextDenovo] get_cns error (#7)


Hi, I have checked files that your uploaded and it seems this is a old version bug, I have fixed in the new version some weeks ago, so pls download the newest version and try again.

**Comment by moold** [comment]
You should re-run all pipeline, not only the get_cns step.

**Comment by moold** [comment]
But, if you only have few tasks with this error, you can check the input.fofn for the sort task, such as: /nextdenovo/01.correct/01.raw_align/03.sort_align.sh.work/sort_align006/input.fofn, and rerurn the minimap task which produced the ovl files in input.fofn. and then re-run the corresponding sort task and cns task.

**Comment by JHAO12321** [comment]
It will cost a lot of time to check whther the new version is ok.
Is nextdenovo suitable for large dataset of pacbio？I know that small dataset is ok, but I haven't seen people to deal with large dataset of pb use nextdenovo.

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by moold** [comment]
We have used NextDenovo  for lots of large genomes  with genome size from 10G to 30G, for large genome size, you can check FAQ IV (use usetempdir option  and adjust -k -w for minimap2). Actually, for large genomes , if you want to correct the raw reads and then do the assembly, you almost have no other choices, that is why we developed NextDenovo.

**Comment by moold** [comment]
I think you can re-run one sort task, and check if this is ok, and then re-run all other unfinished tasks.

**Comment by JHAO12321** [comment]
Yes, I am trying one task now. I hope this will work.

Is this bug specifically for pacbio data? I know many people do large genome data analysis using nextdenovo but they all used nanopore for sequencing. They have used an older version than me but nothing wrong happened.

And I have ssh to the compute node of one get_cns task, there are 24 subtasks but almost all of them are in S stat. Despite I set “-p 24”, the load of cpus is about 1~2. Is there anything wrong of my job? Does this mean, whatever the “-p” is, the task is actually using one cpu when running.


Best Regards
Jiahao
wangjiahao@genomics.cn


发件人: Hu Jiang <notifications@github.com>
答复: Nextomics/NextDenovo <reply@reply.github.com>
日期: 2019年7月24日 星期三 13:07
收件人: Nextomics/NextDenovo <NextDenovo@noreply.github.com>
抄送: "王佳昊(Jiahao Wang)" <wangjiahao@genomics.cn>, Author <author@noreply.github.com>
主题: Re: [Nextomics/NextDenovo] get_cns error (#7)


I think you can re-run one sort task, and check if this is ok, and then re-run all other unfinished tasks.

**Comment by moold** [comment]
1.No, not only for pacbio data. 
2. It means IO wait, please use usetempdir option, especially if usetempdir is on a SSD driver.

**Comment by moold** [comment]
I will close this issue, but if you still have this problem, feel free to reopen it.
